version: '3.9'

services:
  djangocurdapp:
    container_name: djangocurdapp
    build: .
    ports:
      - "8000:8000"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=helloworld
      - PG_HOST=db
      - PG_PORT=5432
      - PG_DB=postgres
    depends_on:
      - db 
  db:
    container_name: db
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=helloworld
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
volumes:
  postgres_data: {}